# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Jan Michael Wallace, Pioneering Inclusive, Future-Forward Technology
email: hello@janmichael.io
description: >- # this means to ignore newlines until "baseurl:"
  Let's craft your minimum awesome product!
# baseurl: "/janmichael.io" # the subpath of your site, e.g. /blog
baseurl: ""
url: "https://janmichael.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jmwii1981
github_username:  jmwii1981

# Build settings
# theme: minima
plugins:
  - jekyll-feed

# Other configuration options
sass:
  sass_dir: styles
  style: compressed


# Optional: Include custom directories so that Jekyll processes them
include:
  - favicons
  - fonts
  - icons
  - images
  - scripts
  - styles

# Optional: If needed, exclude certain directories (you probably don’t need this if not relevant)
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
