title: Jan Michael Wallace
email: hello@janmichael.io
description: "Portfolio"
baseurl: ""
url: "http://janmichael.io"
github_username: jmwii1981
plugins:
  - jekyll-feed
sass:
  sass_dir: _sass
  style: compressed
include:
  - favicons
  - fonts
  - icons
  - images
  - scripts